version: '3.9'

services:

  interpreter:
    build:
      context: .
      target: python-environment
    runtime:
      nvidia
    volumes:
      - /tmp/argus_socket:/tmp/argus_socket
      - ./data:/data
      - .:/app
