version: '3.9'

services:

  interpreter:
    environment:
      - VEHICLE_CONNECTION=/dev/ttyUSB0
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    build:
      context: .
      target: python-environment
    volumes:
      - .:/app
