version: '3.9'

services:

  app:
    build:
      context: .
      target: app
    runtime:
      nvidia
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      - PYTHONPATH=.
      - VEHICLE_CONNECTION=/dev/ttyUSB0
    volumes:
      - /tmp/argus_socket:/tmp/argus_socket
      - ./data:/app/data
