version: '3.9'

services:

  interpreter:
    build:
      context: .
      target: python-environment
    runtime:
      nvidia
    volumes:
      - /tmp/argus_socket:/tmp/argus_socket
      - .:/app

  interpreter-app:
    build:
      context: .
      target: python-environment
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      - VEHICLE_CONNECTION=/dev/ttyUSB0
    volumes:
      - /tmp/argus_socket:/tmp/argus_socket
      - .:/app