version: '3.9'

services:

  app:
    environment:
      - VEHICLE_CONNECTION=/dev/ttyUSB0
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    build:
      context: .
      target: app
    volumes:
      - /tmp/argus_socket:/tmp/argus_socket
      - ./data:/data
