version: '3.9'

services:

  interpreter:
    build:
      context: .
      target: python-environment
    runtime:
      nvidia
    #devices:
    #  - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      - PYTHONPATH=.
    #  - VEHICLE_CONNECTION=/dev/ttyUSB0
    volumes:
      - /tmp/argus_socket:/tmp/argus_socket
      - .:/app
    working_dir: /app
